apiVersion: v1
kind: Service
metadata:
  name: k8s-userservice-service
  namespace: userservice
spec:
  selector:
    app: k8s-userservice
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-userservice-deployment
  namespace: userservice
spec:
  selector:
    matchLabels:
      app: k8s-userservice
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-userservice
    spec:
      containers:
      - name: k8s-userservice
        image: outk/rewardingsites-userservice:v0.0.1
        ports:
        - containerPort: 80
